
print("Welcome to my boolean program.")

print(int(True))
print(int(False))
print(bool(1))
print(bool(0))
print(bool(-42))
print(bool(-41))
print(bool(10))
print(bool(11))
print(bool(11.2))
print(bool(11.1))
print(bool(-11.1))
print(bool(-11.2))
print(True and True)
print(False or True)
print(False or not True)
print(2 + True)
print(2 + False and not True)
print(float(5 + False))
print(float(5 + False or not False))
